### ISSUE TITLE
Warning during build

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mobility-echarging-map#11]
When I run yarn, I get the following message:

```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

Could we remove that file, or is it somehow needed?

**Comment by Piiit** [comment]
@fedriz I've send you an invitation to this repository. Could you have a look at this?

**Comment by fedriz** [comment]
Hi @Piiit ,
> Could we remove that file, or is it somehow needed?

I can't see any problems, I've used only Yarn in order to install dependencies. 
Delete it and do a fresh install everything using **only Yarn**, check if it's all right.

**Comment by Piiit** [comment]
@fedriz Thanks... I did that long time ago, but forgot about this issue :-)
