### ISSUE TITLE
As a consumer of this web comp, I want to have it integrated in the store with all features described

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-mobility-echarging-map#16]
**Prerequisites**
- [x] @rcavaliere will also update metadata inside [wcs-manifest.json](https://github.com/noi-techpark/webcomp-mobility-echarging-map/blob/master/wcs-manifest.json) 

**Check and fix (email by @rcavaliere)**

- [x] si chiede di ingrandire leggermente le dimensioni del logo embedded (attualmente il logo Green Mobility)
> Not done, @Piiit will fix that --> DONE
- [x] ci hanno segnalato che non sempre tutti i testi sono nella lingua corretta. L'obiettivo sarebbe quello di sistemare i testi in maniera definitiva. Su questo ci può dare una mano la STA.
> Not done by Belka, @Piiit will fix that --> DONE
  - [x] the rest can be given to STA (@rcavaliere please check if necessary)
- [x] abbiamo visto che c'è un piccolo bug: se l'utente attiva la geolocalizzazione e clicca su "Non consentire" l'applicativo continua a caricare a vuoto. Qui sarebbe da lasciare all'utente la visualizzazione di default della mappa.
> Checked this, it does not work... If I click on the "my position" icon it does nothing... not even asks me about any permissions --> @rcavaliere Could you please check that also and eventually write to Belka? --> @Piiit fixed it... v1.5.2 contains error messages if something does not work as an overlay box, and disables the spinning icon when something goes wrong
- [x] sembra che la distinzione tra stazioni pubbliche e private ad accesso pubblico sia sempre più importante. STA propone di colorarle in maniera differente così da differenziarle, così come fatto per la stazione H2. Questo perché anche il tipo di esperienza di servizio offerto all'utente potrebbe essere diverso.
> Done with icons that contain a "star", since the types are represented with icons and not colors (using colors here would imply certain states of stations)... is that OK for you @rcavaliere?
> Checked: This has not been done
- [x] il link associato ai POI relativi ad una colonnina di ricarica dovrebbe aprirsi in un altro tab, non nella stessa applicazione.
> Checked: Done
- [x] in caso di utilizzo da mobile, quando uno apre la sezione dei filtri, effettua la sua configurazione e clicca su "Applica" si aspetta che la sezione si chiuda automaticamente e torni alla mappa diversamente configurata. Attualmente invece uno deve chiudere a mano la sezione dei filtri.
> Checked: Done

Additionally:
- [x] Use the new Ninja API for all calls (currently it was mixed with v1 and v2)
- [x] Only use Italian, German and English
- [x] Fix test app

**Comment by Piiit** [comment]
> - [ ] sembra che la distinzione tra stazioni pubbliche e private ad accesso pubblico sia sempre più importante. STA propone di colorarle in maniera differente così da differenziarle, così come fatto per la stazione H2. Questo perché anche il tipo di esperienza di servizio offerto all'utente potrebbe essere diverso.
> Checked: This has not been done

@rcavaliere Should I do this?

**Comment by rcavaliere** [comment]
> @rcavaliere Should I do this?

If it is not a huge effort for you, yes please!

**Comment by Piiit** [comment]
@rcavaliere Should we keep only English, Italian and German as languages?

**Comment by Piiit** [comment]
> If it is not a huge effort for you, yes please!

Done

**Comment by rcavaliere** [comment]
> @rcavaliere Should we keep only English, Italian and German as languages?

Yes!

**Comment by rcavaliere** [comment]
>     * abbiamo visto che c'è un piccolo bug: se l'utente attiva la geolocalizzazione e clicca su "Non consentire" l'applicativo continua a caricare a vuoto. Qui sarebbe da lasciare all'utente la visualizzazione di default della mappa.

If I open the web component full screen, it does not seem responsive to me. Can you please check?

**Comment by Piiit** [comment]
@rcavaliere I fixed the geolocation bug, now I try to reproduce the full screen issue...

**Comment by Piiit** [comment]
I tried with 
```
data:text/html;charset:utf8,<html><head><title>MyWebComponent</title></head><body><e-mobility-map-widget></e-mobility-map-widget><script src="https://cdn.webcomponents.opendatahub.testingmachine.eu/dist/98013c75-f27c-414e-aff9-c58ed760e791/v1.4.0/map_widget.min.js"></script></body></html>
```
...and it is really slow, but it works. Dunno what the issue is thou, we need to get into detail about this. I open another issue for this so we can conclude this one
