### ISSUE TITLE
As a web developer I would like that web-components are responsive so that they can be used in existing web-apps

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-map#19]
- [x] Contact Belka for issues deepening
- [x] Issue found, Belka implementation
- [x] Deplyment of modified web-component in the store

**Comment by Piiit** [comment]
@rcavaliere This can be tested now. It is implemented for this web component.

See https://github.com/noi-techpark/webcomp-mobility-echarging-map#styling

I tested it...

It is not really responsive, just a hardcoded height. I think their might be some tricks to change that height when the container size changes. I have to investigate thou...
