### ISSUE TITLE
charging station power units kW(h)

### ISSUE THREAD

**Issue by gufmar** [noi-techpark/webcomp-mobility-echarging-map#61]
The power stations should show **kW** as max power output, not kWh.
Only the charged amount over each individual charge session time (h) will be in **kWh** then (red marking)

Also the international number formatting seems to be incorrect for DE, IT with dot instead of comma (blue marking)
A charging stations max power for example is either 22,125 kW or 22.125 W. The usual e-charging unit is kW

<img width="225" alt="image" src="https://user-images.githubusercontent.com/13198220/181027245-40fdcd39-7a8e-4ac5-b38c-49a18f079ceb.png">

**Comment by gufmar** [comment]
btw kWh also used as label in the max power filter section

**Comment by dulvui** [comment]
kW labels and international number formatting are now fixed on testing.
I will deploy to production this afternoon after some testing and checking for other internationalization problems.

**Comment by ohnewein** [comment]
Looks great! 👍

**Comment by gufmar** [comment]
LGTM, 
good and quick job guys
